version: "3"

volumes:
  db: 

services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "password"
      MARIADB_DATABASE: "tpr_db"
    volumes:
      - db:/var/lib/mysql
      - ./docker-schema.sql:/docker-entrypoint-initdb.d/schema.sql

  html:
    depends_on:
      - db
    image: tfo-peer-review:development
    #build:
    #  context: ../
    #  dockerfile: ./docker/dockerfile
    restart: unless-stopped
    environment:
      TPR_DB_HOST: "db:3306"
      TPR_DB_USER: "root"
      TPR_DB_PASSWORD: "password"
      TPR_DB_NAME: "tpr_db"
      TPR_API_KEY: "YOUR-API-KEY-HERE"
      PROXY_EXISTS: "false"
      PROXY_HOST: "localhost"
      PROXY_HEADER: "X-Forwarded-For"
    volumes:
      - db:/var/lib/mysql
    ## Other Volume locations:
    #
    # TPR frontend config - enable debugging, etc
    #  - ./volumes/front-config.js:/config.js
    # TPR php/backend config directory
    #  - ./volumes/config:/config
    # Cron logs
    #  - ./volumes/cron.log:/var/log/cron.log
    ports: 
      - 8080:80