<?php
/************************************************************************************** 
 * flag/create Internal-API endpoint
 * 
 * Takes: POST {"code" : "code1"}
 * Returns: {"message" : ...}
 * 
 * Description:
 * This endpoint is the main vector for populating the FlaggedCodes database table. The FlaggedCodes 
 * table is intended to track creatures which may not belong in the site's Creatures table,
 * either because the creature has grown into an adult, died, becomed stunted, etc. 
 * These creatures are tracked by their code (primary key). 
 * 
 * FlaggedCodes is read, and then cleared, during cron events, where the status of all flagged creatures 
 * is re-fetched from TFO, and confirmed invalid creatures are removed.
 * 
 * (Note: the UUID of marking users is also tracked by this endpoint, but is not currently used. In the future
 * it might be used as part of a safeguard to keep one user from unnecessarily/erroneously populating 
 * FlaggedCodes, which could cause server slowdowns on cron events.)
 * 
 * (Also Note: Click table entries are not generated by this endpoint; the click/create endpoint is called seperately
 * by the frontend after marking.)
 * 
 * Frontend-generated UUID is used for this tracking instead of IP or IP-based
 * sessions so that the site works as intended when multiple users are under the same IP.
 * 
 **************************************************************************************/

//header("Access-Control-Allow-Origin: ".$_SERVER['HTTP_ORIGIN']);
header("Access-Control-Allow-Origin: ".$_SERVER['HTTP_REFERER']);
header("Content-Type: application/json; charset=UTF-8");
header("Access-Control-Allow-Methods: POST");
header("Access-Control-Max-Age: 3600");
header("Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With");
header("Access-Control-Allow-Credentials: true");

// If preflight, return only the headers and not the content
if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') { exit; }

// Include database and object files
include_once '../utilities/db.php';
include_once '../utilities/logger.php';
include_once '../utilities/limiter.php';
include_once '../library/flag.php';
include_once '../library/creature.php';

// Instantiate objects
$database = new Database();
$db = $database->getConnection();
$data = json_decode(file_get_contents("php://input"));
$ratelimiter = new RateLimiter($db, $_SERVER['REMOTE_ADDR'], 100, 10);

// Check ip against rate limits
// Click operations have a cost of 2/100 tokens (5 per second)
if (!$ratelimiter->consume(2)){
    http_response_code(429);
    die(json_encode(array("message" => "(429) Too many requests.")));
}

// Validate frontend-generated UUID (stored in the 'tfopr-uuid' browser cookie)
if($_COOKIE['tfopr-uuid']!=null && strlen($_COOKIE['tfopr-uuid'])==36) {
    $uuid = $_COOKIE['tfopr-uuid'];
} else {
    http_response_code(400);
    die(json_encode(array("message" => "(400) Unable to flag creature. UUID token is invalid.")));
}

// Validate incoming creature code
if(!empty($data->code) && strlen($data->code)==5) {
    $code = $data->code;

    // Check if creature exists in server db
    // (if it doesn't, how could someone flag it? This should never happen.)
    $creature = new creature($db);
    $creature->code = $code;
    $creature->readOne();
    if($creature->name==null){
        http_response_code(409);
        die(json_encode(array("message" => "(409) Unable to flag creature. Creature code does not exist in database.")));
    }
} else {
    http_response_code(400);
    die(json_encode(array("message" => "(400) Unable to flag creature. Creature code is invalid.")));
}

// If data validation checks are passed, encode the data object...
$flag = new Flag($db);
$flag->uuid = $uuid;
$flag->code = $code;

// ... and add it to the db table.
if($flag->create()){
    http_response_code(201);
    echo json_encode(array("message" => "(201) Creature was flagged for update."));
} else {
    http_response_code(503);
    echo json_encode(array("error" => "(503) Unable to flag creature."));
}